version: '3.9'

services:
  php-env:
    build: .
    container_name: 'real-estate-app-server'
    volumes:
      - ./src:/var/www/html
    ports:
      - 9004:80
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    container_name: 'db_server'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'dbms_software'
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9006:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge